# 预处理
处理三个数据集文件包含的空值和无效值，同时统一三者的表结构以方便下面的分析处理，将其数据类型进行优化并存储为`csv`文件

In [1]:
import pandas as pd
from functools import partial
import warnings
warnings.filterwarnings("ignore")

## 读取数据

In [2]:
read_2019 = partial(pd.read_excel, sheet_name="Traffic_2019", engine="openpyxl")
read_2020 = partial(pd.read_excel, sheet_name="Traffic_2020", engine="openpyxl")
Florida_2019 = read_2019("../data/美国佛罗里达COVID-19疫情/2020_COVID_Traffic_Data_Florida.xlsx")
Florida_2020 = read_2020("../data/美国佛罗里达COVID-19疫情/2020_COVID_Traffic_Data_Florida.xlsx")
Zhejiang_2019 = read_2019("../data/中国浙江COVID-19疫情/Zhejiang.xlsx")
Zhejiang_2020 = read_2020("../data/中国浙江COVID-19疫情/Zhejiang.xlsx")
Hubei_2019 = read_2019("../data/中国湖北COVID-19疫情/Hubei.xlsx")
Hubei_2020 = read_2020("../data/中国湖北COVID-19疫情/Hubei.xlsx")

In [3]:
data_2019 = [Florida_2019, Zhejiang_2019, Hubei_2019]
data_2020 = [Florida_2020, Zhejiang_2020, Hubei_2020]
data = data_2019 + data_2020

## 原始数据预览

In [4]:
for i, j in zip(data_2019, data_2020):
    display(i)
    display(j)

,SITE ID,POINT_X,POINT_Y,COORDINATE,Urban _1_Rural_0,2019-01-01 00:00:00,2019-01-02 00:00:00,2019-01-03 00:00:00,2019-01-04 00:00:00,2019-01-05 00:00:00,...,2019-06-21 00:00:00,2019-06-22 00:00:00,2019-06-23 00:00:00,2019-06-24 00:00:00,2019-06-25 00:00:00,2019-06-26 00:00:00,2019-06-27 00:00:00,2019-06-28 00:00:00,2019-06-29 00:00:00,2019-06-30 00:00:00
0,30270,488893.165681,2.860710e+06,NAD_1983_UTM_Zone_17N,0.0,4352.0,3829.0,3498.0,3514.0,3878.0,...,3388.0,3743.0,4065.0,2628.0,2418.0,2439.0,2615.0,3324.0,3316.0,3467.0
1,90229,456133.641171,3.032660e+06,NAD_1983_UTM_Zone_17N,1.0,5125.0,6544.0,6658.0,5796.0,4557.0,...,5483.0,4140.0,5081.0,6206.0,6339.0,6179.0,6328.0,5584.0,4281.0,5345.0
2,79918,494587.195767,2.959172e+06,NAD_1983_UTM_Zone_17N,0.0,16340.0,18374.0,19157.0,17368.0,14497.0,...,16544.0,13275.0,15493.0,16896.0,16854.0,17015.0,18346.0,16188.0,12925.0,15566.0
3,40068,402544.191009,3.015863e+06,NAD_1983_UTM_Zone_17N,0.0,4134.0,4986.0,5308.0,5307.0,4087.0,...,4794.0,4128.0,4077.0,4602.0,4645.0,4765.0,4929.0,4326.0,3211.0,5250.0
4,40271,410733.356712,3.010907e+06,NAD_1983_UTM_Zone_17N,0.0,5664.0,6614.0,6890.0,6406.0,5364.0,...,5678.0,4907.0,4978.0,5708.0,5710.0,5703.0,5878.0,5406.0,4490.0,3811.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,550349,196127.351009,3.392133e+06,NAD_1983_UTM_Zone_17N,0.0,10427.0,12548.0,12789.0,13130.0,11737.0,...,0.0,0.0,0.0,9590.0,12207.0,12542.0,13797.0,14493.0,12611.0,10798.0
255,879947,565215.660600,2.861861e+06,NAD_1983_UTM_Zone_17N,1.0,25773.0,37694.0,39422.0,32161.0,23004.0,...,31900.0,20295.0,26700.0,38565.0,38586.0,38811.0,39888.0,31469.0,19983.0,11704.0
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Total,NaN,NaN,NaN,NaN,7863244.0,9511449.0,9633075.0,9171470.0,8078090.0,...,9732664.0,8290972.0,8209295.0,9110656.0,9158065.0,9552869.0,9944706.0,9822668.0,8302653.0,7325977.0

,SITE ID,POINT_X,POINT_Y,COORDINATE,Urban _1_Rural_0,2020-01-01 00:00:00,2020-01-02 00:00:00,2020-01-03 00:00:00,2020-01-04 00:00:00,2020-01-05 00:00:00,...,2020-05-23 00:00:00,2020-05-24 00:00:00,2020-05-25 00:00:00,2020-05-26 00:00:00,2020-05-27 00:00:00,2020-05-28 00:00:00,2020-05-29 00:00:00,2020-05-30 00:00:00,2020-05-31 00:00:00,2020-06-01 00:00:00
0,30270,488893.165681,2.860710e+06,NAD_1983_UTM_Zone_17N,0.0,4490.0,4093.0,4101.0,4078.0,4354.0,...,3770.0,2307.0,2705.0,1752.0,1640.0,1774.0,2515.0,3156.0,3893.0,2231.0
1,90229,456133.641171,3.032660e+06,NAD_1983_UTM_Zone_17N,1.0,5043.0,6657.0,5939.0,4427.0,5480.0,...,4301.0,3408.0,3479.0,6150.0,0.0,0.0,0.0,0.0,0.0,2924.0
2,79918,494587.195767,2.959172e+06,NAD_1983_UTM_Zone_17N,0.0,16324.0,19858.0,17848.0,14527.0,17224.0,...,14048.0,10584.0,12012.0,15819.0,15544.0,15764.0,17863.0,13195.0,12087.0,16076.0
3,40068,402544.191009,3.015863e+06,NAD_1983_UTM_Zone_17N,0.0,4094.0,5224.0,4506.0,3723.0,4316.0,...,3841.0,2783.0,3057.0,4635.0,4617.0,4523.0,5028.0,3701.0,3180.0,4337.0
4,40271,410733.356712,3.010907e+06,NAD_1983_UTM_Zone_17N,0.0,5932.0,7150.0,6500.0,5493.0,5995.0,...,5872.0,4288.0,4463.0,5885.0,6056.0,5886.0,6569.0,5837.0,4992.0,5786.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,550349,196127.351009,3.392133e+06,NAD_1983_UTM_Zone_17N,0.0,10139.0,12825.0,13170.0,11883.0,11113.0,...,10449.0,9564.0,9628.0,10505.0,10949.0,11645.0,12323.0,11164.0,9853.0,13471.0
255,879947,565215.660600,2.861861e+06,NAD_1983_UTM_Zone_17N,1.0,23226.0,34888.0,29010.0,19652.0,28168.0,...,16291.0,14652.0,24141.0,33382.0,33683.0,34819.0,29002.0,18491.0,24522.0,19887.0
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Total,NaN,NaN,NaN,NaN,7913180.0,9975130.0,9153143.0,8136673.0,8103988.0,...,6339913.0,5485174.0,5928806.0,7236335.0,7356067.0,7771458.0,7845006.0,6763741.0,6301980.0,7112154.0

,观测点名称,地点,经度,纬度,2019-01-01 00:00:00,2019-01-02 00:00:00,2019-01-03 00:00:00,2019-01-04 00:00:00,2019-01-05 00:00:00,2019-01-06 00:00:00,...,2019-05-23 00:00:00,2019-05-24 00:00:00,2019-05-25 00:00:00,2019-05-26 00:00:00,2019-05-27 00:00:00,2019-05-28 00:00:00,2019-05-29 00:00:00,2019-05-30 00:00:00,2019-05-31 00:00:00,2019-06-01 00:00:00
0,父子岭,江苏省无锡市宜兴市G25(长深高速),119.903082,31.227609,20129.0,18156.0,21320.0,19095.0,20457.0,19176.0,...,22537.0,24406.0,21940.0,21268.0,21072.0,22168.0,22826.0,23624.0,24536.0,23877.0
1,浙沪南主线,上海市金山区G15(沈海高速),121.276483,30.734369,17668.0,9960.0,10072.0,10867.0,8891.0,9546.0,...,10148.0,11246.0,10101.0,11689.0,10004.0,10566.0,10804.0,10256.0,10989.0,9726.0
2,淡竹,浙江省杭州市淳安县S06(零六省道),119.233016,29.563801,322.0,327.0,350.0,367.0,381.0,339.0,...,532.0,650.0,757.0,514.0,511.0,544.0,573.0,552.0,845.0,763.0
3,千岛湖,浙江省杭州市淳安县S32(杭新景高速),119.163469,29.605547,3911.0,2879.0,3210.0,3811.0,4056.0,3383.0,...,3989.0,5270.0,5693.0,3874.0,3883.0,4069.0,3866.0,3867.0,4710.0,5653.0
4,场口,浙江省杭州市富阳区,119.877056,29.910195,2418.0,2119.0,2449.0,2416.0,2314.0,2136.0,...,2801.0,3087.0,3146.0,2541.0,2684.0,2860.0,2926.0,2667.0,2786.0,2931.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,舟山,浙江省舟山市定海区G9211(甬舟高速),122.010037,30.054467,10881.0,7226.0,7561.0,8110.0,8497.0,7525.0,...,9586.0,11892.0,11987.0,8308.0,8607.0,9530.0,9232.0,8710.0,10546.0,12074.0
427,册子,浙江省舟山市定海区金山路,121.946617,30.082935,691.0,704.0,692.0,629.0,619.0,541.0,...,750.0,762.0,673.0,561.0,625.0,753.0,793.0,728.0,654.0,657.0
428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,sum,NaN,NaN,NaN,1807004.0,1586381.0,1643952.0,1686265.0,1550240.0,1506015.0,...,1836556.0,1982465.0,1849126.0,1697399.0,1779304.0,1803765.0,1805648.0,1809117.0,1889376.0,1785131.0

,观测点名称,地点,经度,纬度,2020-01-01 00:00:00,2020-01-02 00:00:00,2020-01-03 00:00:00,2020-01-04 00:00:00,2020-01-05 00:00:00,2020-01-06 00:00:00,...,2020-05-23 00:00:00,2020-05-24 00:00:00,2020-05-25 00:00:00,2020-05-26 00:00:00,2020-05-27 00:00:00,2020-05-28 00:00:00,2020-05-29 00:00:00,2020-05-30 00:00:00,2020-05-31 00:00:00,2020-06-01 00:00:00
0,父子岭,江苏省无锡市宜兴市G25(长深高速),119.903082,31.227609,8197.0,8342.0,8430.0,3543.0,558.0,475.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,浙沪南主线,上海市金山区G15(沈海高速),121.276483,30.734369,3382.0,3911.0,4324.0,1453.0,69.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,淡竹,浙江省杭州市淳安县S06(零六省道),119.233016,29.563801,446.0,324.0,338.0,437.0,423.0,528.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,千岛湖,浙江省杭州市淳安县S32(杭新景高速),119.163469,29.605547,4690.0,4001.0,3945.0,3684.0,4695.0,2921.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,场口,浙江省杭州市富阳区,119.877056,29.910195,1953.0,2255.0,2262.0,2304.0,2118.0,1560.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,舟山,浙江省舟山市定海区G9211(甬舟高速),122.010037,30.054467,4092.0,2961.0,3257.0,4133.0,4011.0,4494.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,册子,浙江省舟山市定海区金山路,121.946617,30.082935,851.0,858.0,842.0,791.0,869.0,927.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,sum,NaN,NaN,NaN,1578400.0,1584404.0,1583224.0,1583721.0,1581640.0,1583689.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,观测点名称,经度,纬度,2019-01-01 00:00:00,2019-01-02 00:00:00,2019-01-03 00:00:00,2019-01-04 00:00:00,2019-01-05 00:00:00,2019-01-06 00:00:00,2019-01-07 00:00:00,...,2019-05-23 00:00:00,2019-05-24 00:00:00,2019-05-25 00:00:00,2019-05-26 00:00:00,2019-05-27 00:00:00,2019-05-28 00:00:00,2019-05-29 00:00:00,2019-05-30 00:00:00,2019-05-31 00:00:00,2019-06-01 00:00:00
0,安福寺,111.596,30.5371,2383.0,1852.0,1815.0,2026.0,2107.0,2141.0,1862.0,...,1776.0,2038.0,1996.0,2059.0,1815.0,1819.0,1814.0,1801.0,1934.0,2503.0
1,安居,113.178,31.7628,924.0,711.0,617.0,597.0,592.0,573.0,610.0,...,717.0,758.0,772.0,715.0,645.0,692.0,659.0,723.0,739.0,776.0
2,安陆,113.706,31.2003,2302.0,1921.0,1929.0,2056.0,2033.0,1898.0,1911.0,...,1875.0,2326.0,2022.0,1818.0,1962.0,1938.0,1983.0,1953.0,2445.0,2438.0
3,安山,114.281,30.1606,2305.0,1895.0,1898.0,2021.0,2178.0,2140.0,2130.0,...,2755.0,3020.0,2440.0,2332.0,2673.0,2592.0,2819.0,2531.0,2895.0,3449.0
4,巴东,110.337,30.6225,1229.0,1074.0,1210.0,1275.0,1182.0,1254.0,1320.0,...,1392.0,1394.0,1312.0,1374.0,1404.0,1392.0,1416.0,1278.0,1417.0,1336.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,秭归港,110.959,30.8541,2865.0,2486.0,2145.0,2339.0,2388.0,2294.0,2472.0,...,863.0,932.0,845.0,853.0,946.0,828.0,880.0,848.0,792.0,892.0
367,总路咀,115.061,30.7023,1700.0,1356.0,1315.0,1421.0,1696.0,1451.0,1394.0,...,1312.0,1328.0,1307.0,1156.0,1146.0,1285.0,1199.0,1199.0,1454.0,1552.0
368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,sum,NaN,NaN,962961.0,785348.0,799650.0,834178.0,816843.0,810830.0,809486.0,...,872532.0,958054.0,819251.0,850583.0,867913.0,854305.0,853216.0,842473.0,927777.0,973919.0

,观测点名称,经度,纬度,20200101,20200102,20200103,20200104,20200105,20200106,20200107,...,20200621,20200622,20200623,20200624,20200625,20200626,20200627,20200628,20200629,20200630
0,湖北安福寺站,111.589839,30.530728,1302.0,1112.0,1572.0,1344.0,868.0,848.0,972.0,...,2167.0,1814.0,1968.0,2845.0,3798.0,2632.0,2009.0,1713.0,1850.0,2012.0
1,湖北安居站,113.165121,31.758355,974.0,764.0,717.0,737.0,668.0,649.0,617.0,...,745.0,714.0,770.0,1333.0,1647.0,1047.0,790.0,754.0,677.0,759.0
2,湖北安陆站,113.693308,31.196966,4575.0,4209.0,4670.0,4398.0,3845.0,3875.0,4090.0,...,2202.0,2329.0,2519.0,4802.0,4909.0,2987.0,2599.0,2172.0,2438.0,2516.0
3,湖北安山站,114.269461,30.157241,2698.0,2492.0,2290.0,2197.0,2178.0,2056.0,2076.0,...,2323.0,2351.0,2229.0,3606.0,4562.0,2706.0,2224.0,1900.0,1626.0,1999.0
4,湖北巴东北站,110.265908,31.944497,1732.0,1658.0,1929.0,1664.0,1532.0,1659.0,1712.0,...,1278.0,1361.0,1405.0,1898.0,1895.0,1648.0,1430.0,1358.0,1386.0,1501.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,湖北总路咀站,115.048978,30.698816,1929.0,1619.0,1419.0,1573.0,1484.0,1611.0,1543.0,...,997.0,1039.0,1032.0,1898.0,2226.0,1372.0,1082.0,827.0,883.0,995.0
363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,Sum,NaN,NaN,877696.0,834920.0,840811.0,794766.0,765877.0,763512.0,794119.0,...,757035.0,774265.0,818438.0,1145441.0,1185861.0,1046249.0,975753.0,773586.0,756407.0,813664.0

**佛罗里达数据**：
* 包含256个地点，有无效行
* 2019和2020年数据的日期范围不一致
* 坐标需要转换为WGS_84

**浙江数据**:
* 包含428个地点，有一行聚合数据需要删除
* 既有地点名又有具体位置名，可在后续合为一列
* 两年的日期范围一致，但2020年包含大量空列

**湖北数据**:
* 包含363个地点，2019年数据有大量空行
* 日期范围一致且都有效

## 删除无效行

### 佛罗里达州

In [5]:
Florida_2019.dropna(inplace=True)
Florida_2020.dropna(inplace=True)

### 浙江

In [6]:
Zhejiang_2019.drop(labels=428, inplace=True)
Zhejiang_2020.drop(labels=428, inplace=True)

### 湖北

In [7]:
Hubei_2019.dropna(axis=0, how="all", inplace=True)
Hubei_2019.drop(labels=370, inplace=True)
Hubei_2020.drop(labels=363, inplace=True)
Hubei_2020.drop(labels=364, inplace=True)
Hubei_2020.drop(labels=365, inplace=True)
Hubei_2020.drop(labels=366, inplace=True)

In [8]:
Hubei_2020["观测点名称"] = Hubei_2020["观测点名称"].apply(lambda x: x[2:-1])

In [9]:
site_set = list(set(Hubei_2019["观测点名称"].values) & set(Hubei_2020["观测点名称"].values))

In [10]:
Hubei_2019 = Hubei_2019[Hubei_2019["观测点名称"].isin(site_set)]
Hubei_2020 = Hubei_2020[Hubei_2020["观测点名称"].isin(site_set)]

In [11]:
Hubei_2019.reset_index(drop=True, inplace=True)
Hubei_2020.reset_index(drop=True, inplace=True)

## 分离数据，并统一时间区间

含有大量空值的日期需要移除，两张数据对齐方式为按星期对齐，2019.01.01为星期二，2020.01.01为星期三，所以数据统计的开始时间对于2019年为一月二日，对于2020年为一月一日，结束时间按公共日期取最大数为准

### 佛罗里达

In [12]:
timeindex_2019 = pd.date_range("2019-01-02", "2019-06-03")
timeindex_2020 = pd.date_range("2020-01-01", "2020-06-01")

In [13]:
Florida_site = Florida_2019.iloc[:, :5].copy()

In [14]:
Florida_2019 = pd.DataFrame(Florida_2019.iloc[:, 6:159], columns=timeindex_2019, index=Florida_2019.index)
Florida_2020 = pd.DataFrame(Florida_2020.iloc[:, 5:158], columns=timeindex_2020, index=Florida_2020.index)

####  佛罗里达坐标数据转换

In [15]:
from pyproj import CRS
import pyproj

crs_NAD83_UTM_zone_17N = CRS.from_epsg(26917)
crs_WGS_84 = CRS.from_epsg(4326)
transformer = pyproj.Transformer.from_crs(crs_NAD83_UTM_zone_17N, crs_WGS_84)
Lat, Lon =  transformer.transform(Florida_site["POINT_X"].values, Florida_site["POINT_Y"].values)
Florida_site["POINT_X"] = Lat
Florida_site["POINT_Y"] = Lon
Florida_site.rename(columns={"POINT_X": "Latitude", "POINT_Y": "Longitude"}, inplace=True)
Florida_site["COORDINATE"] = "WGS_84"

Florida_site.rename(columns={"Urban _1_Rural_0": "Urban or Rural"}, inplace=True) #顺便改名
Florida_site["Urban or Rural"][Florida_site["Urban or Rural"] == 1] = "Urban"
Florida_site["Urban or Rural"][Florida_site["Urban or Rural"] == 0] = "Rural"

### 浙江

In [16]:
Zhejiang_site = Zhejiang_2019.iloc[:, :4].copy()
Zhejiang_site.rename(columns={"观测点名称": "SITE ID",
                              "地点": "SITE",
                              "经度": "Longitude",
                              "纬度": "Latitude"
                             }, inplace=True)

In [17]:
Zhejiang_2020.dropna(axis=1, how="all", inplace=True)

In [18]:
timeindex_2019 = pd.date_range("2019-01-02", "2019-05-02")
timeindex_2020 = pd.date_range("2020-01-01", "2020-04-30")
Zhejiang_2019 = pd.DataFrame(Zhejiang_2019.iloc[:, 5:126], columns=timeindex_2019, index=Zhejiang_2019.index)
Zhejiang_2020 = pd.DataFrame(Zhejiang_2020.iloc[:, 4:], columns=timeindex_2020, index=Zhejiang_2020.index)

### 湖北

In [19]:
Hubei_site = Hubei_2019.iloc[:, :3].copy()
Hubei_site.rename(columns={"观测点名称": "SITE ID",
                              "经度": "Longitude",
                              "纬度": "Latitude"
                             }, inplace=True)

In [20]:
timeindex_2019 = pd.date_range("2019-01-02", "2019-06-01")
timeindex_2020 = pd.date_range("2020-01-01", "2020-05-30")

In [21]:
Hubei_2019 = pd.DataFrame(Hubei_2019.iloc[:, 4:], columns=timeindex_2019, index=Hubei_2019.index)
Hubei_2020 = pd.DataFrame(Hubei_2020.iloc[:, 3:154], index=Hubei_2020.index)
Hubei_2020.columns = timeindex_2020

## 数据填充

原始数据中有空值和0值，这里先对空值填充为0，再通过取最近10个非0流量平均值的方法填充0值

In [22]:
data_2019 = [Florida_2019, Zhejiang_2019, Hubei_2019]
data_2020 = [Florida_2020, Zhejiang_2020, Hubei_2020]
data = data_2019 + data_2020

### 填充空值

In [23]:
for i in data:
    i.fillna(0, inplace=True)

### 填充0值

In [24]:
def del0(volume: pd.DataFrame, days: int=0):
    date = len(volume.columns)
    site = len(volume)
    for i in range(site):
        for j in range(date):
            if volume.iloc[i, j] <= 1:
                left, right = j - 1, j + 1
                n = 0
                sum_volume = 0
                while n < days and left>=0 or right < date:
                    if left >= 0:
                        if volume.iloc[i, left] > 1:
                            sum_volume += volume.iloc[i, left]
                            n += 1
                        left -= 1
                    if right < date:
                        if volume.iloc[i, right] > 1:
                            sum_volume += volume.iloc[i, right] 
                            n += 1
                        right += 1
                if n:
                    volume.iloc[i, j] = sum_volume / n
            else:
                continue

In [25]:
for i in data:
    del0(i)

## 保存数据

In [26]:
Florida_2019.to_csv("../data/美国佛罗里达COVID-19疫情/Florida_2019.csv", index=False)
Florida_2020.to_csv("../data/美国佛罗里达COVID-19疫情/Florida_2020.csv", index=False)
Florida_site.to_csv("../data/美国佛罗里达COVID-19疫情/Florida_site.csv", index=False)

Zhejiang_2019.to_csv("../data/中国浙江COVID-19疫情/Zhejiang_2019.csv", index=False)
Zhejiang_2020.to_csv("../data/中国浙江COVID-19疫情/Zhejiang_2020.csv", index=False)
Zhejiang_site.to_csv("../data/中国浙江COVID-19疫情/Zhejiang_site.csv", index=False)

Hubei_2019.to_csv("../data/中国湖北COVID-19疫情/Hubei_2019.csv", index=False)
Hubei_2020.to_csv("../data/中国湖北COVID-19疫情/Hubei_2020.csv", index=False)
Hubei_site.to_csv("../data/中国湖北COVID-19疫情/Hubei_site.csv", index=False)

## 总结

* 对数据进行了日期区间的统一，按照星期对齐的规则
* 对数据进行了填充
* 分离了数据，统一三个数据的列名，方便接下来的处理